import { useState, useEffect, useReducer } from 'react';

import Head from 'next/head';
import Image from 'next/image';

import { Header } from '../components/Header';
import styles from '../styles/Home.module.css';

const INITIAL_STATE = {
  counter: 1,
};

function reducer(state, action) {
  const { type } = action;

  switch (type) {
    case 'increment': {
      return {
        counter: state.counter + 1,
      };
    }

    case 'decrement': {
      return {
        counter: state.counter - 1,
      };
    }
  }
}

export default function Home() {
  // hooks states
  // const [counter, setCounter] = useState(1);

  // const handleIncrementCounter = () => setCounter((previousCounter) => previousCounter + 1);

  // const handleDecrementCounter = () => setCounter((previousCounter) => previousCounter - 1);

  // reducers hooks
  const [state, dispatch] = useReducer(reducer, INITIAL_STATE);

  const { counter } = state;

  // handlers
  const handleIncrementCounter = () => dispatch({ type: 'increment' });

  const handleDecrementCounter = () => dispatch({ type: 'decrement' });

  // effects

  useEffect(() => {
    const setTimeoutId = setTimeout(() => {
      console.log(`on useEffect ${counter}`);
      console.log(`Executed at ${counter * 100}ms`);
    }, counter * 100);

    return () => clearTimeout(setTimeoutId);
  }, [counter]);

  useEffect(() => {
    const controller = new AbortController();

    fetch('https://api.twitter.com/1', { signal: controller.signal })
      .then(function (response) {})
      .catch(function (e) {});

    return () => controller.abort();
  }, [counter]);

  useEffect(() => {
    const $button = document.querySelector('.btn');
    const onClick = () => console.log('button clicked');

    $button?.addEventListener('click', onClick);

    return () => $button?.removeEventListener('click', onClick);
  }, [counter]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Header></Header>

        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Counter is <code className={styles.code}>{counter}</code>
        </p>

        <button onClick={handleIncrementCounter}>Increment +</button>
        <button onClick={handleDecrementCounter}>Decrement -</button>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/master/examples' className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
